---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

base_packages:
  - deltarpm
  - "@Development tools"
  - git
  - python-setuptools
  - wget
  - redhat-lsb-core
  - libselinux-python
  - yum-plugin-priorities

debug_packages:
  - net-tools
  - lsof
  - tcpdump
  - sysstat
  - psmisc

# Jenkins environment vars used in tasks/templates
job_name: "{{ lookup('env', 'JOB_NAME')|default('nojob') }}"
build_number: "{{ lookup('env', 'BUILD_NUMBER')|default('nobuild') }}"

log_root: "/var/log/weirdo"
log_destination: "{{ log_root }}/{{ job_name }}/{{ build_number }}"
log_paths:
  - /var/log/audit
  - /etc/ansible

debug_commands:
  cpuinfo:
    command: "cat /proc/cpuinfo"
  df:
    command: "df -h"
  dmesg:
    command: "dmesg -T"
  fdisk:
    command: "fdisk -l"
  getenforce:
    command: "getenforce"
  iptables:
    command: "iptables -vnL"
  iptables_nat:
    command: "iptables -vnL -t nat"
  iptables_mangle:
    command: "iptables -vnL -t mangle"
  journalctl:
    command: "journalctl --no-pager"
  lsmod:
    command: "lsmod"
  lsof:
    command: "lsof -P"
  lsof_network:
    command: "lsof -Pni"
  meminfo:
    command: "cat /proc/meminfo"
  mounts:
    command: "cat /proc/mounts |column -t"
  netstat:
    command: "netstat -ntlp"
  pstree:
    command: "pstree -p"
  sysstat:
    command: "sar -A -f /var/log/sa/*"
  sysctl:
    command: "sysctl -a"
  repolist:
    command: "yum repolist -v"
  rpm_packages:
    command: "rpm -qa"
