---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Request node(s) from ci.centos.org
  cico:
    action: "get"
    api_key: "{{ api_keyÂ }}"
    arch: "{{ arch }}"
    release: "{{ release }}"
    count: "{{ count }}"
  register: cico_data

- name: Add requested nodes to hosts file
  add_host:
    name: "{{ cico_data.results.hosts[item].hostname }}"
    groups: "openstack_nodes"
    ansible_fqdn: "{{ cico_data.results.hosts[item].hostname }}"
    ansible_ssh_user: "root"
    ansible_ssh_private_key_file: "{{ private_key }}"
    ansible_ssh_host: "{{ cico_data.results.hosts[item].ip_address }}"
  with_items: "{{ cico_data.results.hosts }}"

- name: Disable requiretty to support SSH pipelining
  lineinfile:
    dest: "/etc/sudoers"
    regexp: '^Defaults\s+requiretty$'
    state: "absent"
    validate: "/usr/sbin/visudo -cf %s"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openstack_nodes'] }}"

- name: Setup custom facts directory
  file:
    state: "directory"
    recurse: "yes"
    path: "/etc/ansible/facts.d"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openstack_nodes'] }}"

- name: Install ci custom facts for provisioning traceability
  vars:
    BUILD_URL: "{{ lookup('env', 'BUILD_URL')|default('') }}"
    JENKINS_URL: "{{ lookup('env', 'JENKINS_URL')|default('') }}"
  template:
    src: "templates/ci.fact.j2"
    dest: "/etc/ansible/facts.d/ci.fact"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openstack_nodes'] }}"

- name: Refresh facts
  setup:
    filter: "ansible_local"
